import Foundation

struct BankQuestion: Identifiable, Hashable, Sendable {
    let id: String
    let task: WritingTask
    let title: String
    let prompt: String
}

/// Built-in practice prompts. All are original; none reproduces a past exam paper.
enum QuestionBank {
    static func questions(for task: WritingTask) -> [BankQuestion] {
        let sample = BankQuestion(id: "\(task.rawValue)-0", task: task, title: task == .kaoyanSmall ? "原创练习 · 邀请信" : "原创练习", prompt: task.sampleQuestion)
        let imported = ((try? CETQuestionBank.entries()) ?? []).filter { $0.task == task.rawValue && $0.hasPrompt }.map { BankQuestion(id: $0.id, task: task, title: $0.title, prompt: $0.prompt) }
        return imported + [sample] + extra(task).enumerated().map { BankQuestion(id: "\(task.rawValue)-\($0.offset + 1)", task: task, title: $0.element.0, prompt: $0.element.1) }
    }
    static var all: [BankQuestion] { WritingTask.allCases.flatMap(questions(for:)) }

    /// Question text normalized the same way History groups attempts.
    static func key(_ prompt: String) -> String {
        prompt.replacingOccurrences(of: "\r\n", with: "\n").replacingOccurrences(of: "\r", with: "\n").trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private static func extra(_ task: WritingTask) -> [(String, String)] {
        switch task {
        case .kaoyanSmall: [
            ("道歉信 · 错过会面", "You missed a meeting with Professor Smith, who had agreed to discuss your research proposal with you. Write an email to apologise. You should\n1. explain why you missed the meeting,\n2. express your regret, and\n3. suggest another time to meet.\nWrite about 100 words. Do not use your own name. Use “Li Ming” instead."),
            ("推荐信 · 推荐一本书", "Your friend Jack, an international student, wants to improve his understanding of Chinese society and has asked you to recommend a book. Write him an email to\n1. recommend a book,\n2. briefly introduce its content, and\n3. explain why it would help him.\nWrite about 100 words. Do not use your own name. Use “Li Ming” instead."),
            ("通知 · 招募志愿者", "The university library is recruiting student volunteers to help with a new reading-promotion programme. Write a notice to\n1. briefly describe the programme,\n2. state the requirements for volunteers, and\n3. explain how to apply.\nWrite about 100 words. Do not sign your own name. Use “University Library” instead."),
            ("投诉信 · 网购延误", "You ordered a desk lamp online three weeks ago, but it has not arrived and the customer service line does not respond. Write a letter to the company to\n1. describe the problem,\n2. explain how it has affected you, and\n3. state what you expect them to do.\nWrite about 100 words. Do not use your own name. Use “Li Ming” instead."),
            ("询问信 · 暑期项目", "You have learned that Professor Brown is running a summer research programme on urban environments. Write an email to\n1. introduce yourself briefly,\n2. express your interest in the programme, and\n3. ask for details about how to apply.\nWrite about 100 words. Do not use your own name. Use “Li Ming” instead.")
        ]
        case .kaoyanLarge: [
            ("图画 · 屏幕前的家庭晚餐", "A drawing shows a family of four sitting at a dinner table. Each member is looking down at a phone; the food in the middle of the table has gone cold. On the wall a clock reads 8 p.m. The caption reads “Together, alone”.\nWrite an essay of 160–200 words in which you should\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments."),
            ("图画 · 种树的祖孙", "A drawing shows an old man and a young boy planting a small tree. The old man is holding the young tree steady while the boy fills the hole with soil. Behind them stands a tall, leafy tree. The caption reads “Passing it on”.\nWrite an essay of 160–200 words in which you should\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments."),
            ("图画 · 证书垒成的台阶", "A drawing shows a student standing on a tall pile of books labelled “certificates” to reach a door labelled “career”. The student is reaching for the door, but the handle, labelled “real ability”, is far out of reach.\nWrite an essay of 160–200 words in which you should\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments."),
            ("图画 · 照亮夜路的书灯", "A drawing shows a person walking along a dark forest path at night. They are holding up an open book that gives off light like a lamp, illuminating the path ahead. The caption reads “Light the way”.\nWrite an essay of 160–200 words in which you should\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments."),
            ("图画 · 两条起跑线", "A drawing shows two runners on a track. One stands at the start line and keeps looking back at the crowd. The other is already running, eyes on the road ahead. A sign beside the track reads “The race is your own”.\nWrite an essay of 160–200 words in which you should\n1) describe the drawing briefly,\n2) explain its intended meaning, and\n3) give your comments.")
        ]
        case .kaoyan2Small: [
            ("通知 · 二手书交换", "Suppose your class is going to hold a second-hand book exchange on campus. Write a notice to\n1) introduce the event, and\n2) encourage students to take part.\nWrite your answer in about 100 words.\nDo not use your own name in the notice. Use “Li Ming” instead."),
            ("邮件 · 推迟小组讨论", "Suppose you have to postpone a group discussion you arranged with your classmate Tom. Write him an email to\n1) explain the reason, and\n2) suggest a new time.\nWrite your answer in about 100 words.\nDo not use your own name in your email. Use “Li Ming” instead."),
            ("邮件 · 推荐周末去处", "Your friend Lucy, an exchange student, wants to spend a weekend outside the city. Write her an email to\n1) recommend a place, and\n2) give her some practical tips.\nWrite your answer in about 100 words.\nDo not use your own name in your email. Use “Li Ming” instead."),
            ("邮件 · 感谢导师指导", "Suppose your research report won a prize with the help of Professor Brown. Write him an email to\n1) express your thanks, and\n2) tell him about your plan for further study.\nWrite your answer in about 100 words.\nDo not use your own name in your email. Use “Li Ming” instead.")
        ]
        case .kaoyan2Large: [
            ("图表 · 外卖使用频率", "Write an essay based on the chart below. In your essay, you should\n1) describe and interpret the chart, and\n2) give your comments.\nWrite your answer in about 150 words.\n\n【图表数据】某市大学生每周点外卖次数调查（占受访学生比例）\n0 次：12%\n1–2 次：35%\n3–5 次：38%\n6 次及以上：15%"),
            ("图表 · 城市共享单车", "Write an essay based on the chart below. In your essay, you should\n1) describe and interpret the chart, and\n2) give your comments.\nWrite your answer in about 150 words.\n\n【图表数据】某市共享单车日均骑行量（单位：万次）\n2019 年：45\n2020 年：38\n2021 年：52\n2022 年：61\n2023 年：70"),
            ("图表 · 选择工作的考虑因素", "Write an essay based on the chart below. In your essay, you should\n1) describe and interpret the chart, and\n2) give your comments.\nWrite your answer in about 150 words.\n\n【图表数据】某高校毕业生选择工作时最看重的因素\n个人发展空间：36%\n薪资待遇：29%\n工作地点：18%\n工作稳定性：12%\n其他：5%"),
            ("图表 · 博物馆线上展览", "Write an essay based on the chart below. In your essay, you should\n1) describe and interpret the chart, and\n2) give your comments.\nWrite your answer in about 150 words.\n\n【图表数据】某省博物馆线下参观与线上观展人次（单位：万人次）\n2021 年：线下 320，线上 150\n2022 年：线下 290，线上 260\n2023 年：线下 410，线上 380")
        ]
        case .cet6Writing: [
            ("终身学习", "For this part, you are allowed 30 minutes to write an essay on the importance of lifelong learning. You can start your essay with the sentence “Learning is a treasure that will follow its owner everywhere.” You should write at least 150 words but no more than 200 words."),
            ("线上与线下学习", "For this part, you are allowed 30 minutes to write an essay on how college students can strike a balance between online and offline learning. You should write at least 150 words but no more than 200 words."),
            ("失败的价值", "For this part, you are allowed 30 minutes to write an essay on the value of failure. You can start your essay with the sentence “Failure is not the opposite of success, but part of it.” You should write at least 150 words but no more than 200 words."),
            ("与专业相关的兼职", "For this part, you are allowed 30 minutes to write an essay on whether college students should take part-time jobs related to their majors. You should state your view and support it with reasons. You should write at least 150 words but no more than 200 words."),
            ("耐心与目标", "For this part, you are allowed 30 minutes to write an essay on the role of patience in achieving one’s goals. You should give examples to illustrate your point. You should write at least 150 words but no more than 200 words.")
        ]
        case .ieltsTask1: [
            ("折线图 · 家庭能源", "The line graph below shows the average annual energy use per household in one country, by source, from 1990 to 2020 (in units of 1,000 kWh). Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nSource — 1990 / 2000 / 2010 / 2020\nGas: 9.0 / 10.5 / 9.5 / 7.5\nElectricity: 4.0 / 4.5 / 5.5 / 6.5\nOil: 3.5 / 2.5 / 1.5 / 0.5\nSolar: 0 / 0.2 / 1.0 / 2.5\n\nWrite at least 150 words."),
            ("柱状图 · 图书馆设施", "The bar chart below shows the percentage of university students who used four library facilities at least once a week in 2010 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nFacility — 2010 → 2020\nBook loans: 68% → 35%\nQuiet study rooms: 45% → 62%\nComputers: 52% → 20%\nGroup study rooms: 15% → 48%\n\nWrite at least 150 words."),
            ("流程图 · 再生纸", "The diagram below shows how recycled paper is produced. Summarise the information by selecting and reporting the main features.\n\nStages in order:\n1. Used paper is collected from homes and offices.\n2. It is sorted by type and grade at a recycling centre.\n3. Paper is mixed with water and chemicals and pulped.\n4. The pulp is screened to remove staples, plastic and glue.\n5. Ink is removed in a de-inking tank.\n6. The clean pulp is pressed and dried on heated rollers.\n7. The finished paper is rolled, cut and delivered to manufacturers.\n\nWrite at least 150 words."),
            ("地图 · 小镇中心变化", "The maps below show the centre of a small town in 2005 and today. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\n2005: A main road runs east–west through the centre. North of the road: a car park and a row of small shops. South of the road: a bus station and a large park with a pond.\nToday: The main road is pedestrianised; traffic uses a new ring road. The car park has become a shopping centre. The shops remain. The bus station has moved to the ring road and its site is now apartments. The park is smaller, and a café has been built beside the pond.\n\nWrite at least 150 words."),
            ("饼图 · 家庭开支", "The pie charts below show how the average household in one country spent its income in 1980 and 2020. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nCategory — 1980 / 2020\nFood: 35% / 18%\nHousing: 20% / 32%\nTransport: 12% / 14%\nLeisure: 8% / 15%\nEducation: 5% / 9%\nOther: 20% / 12%\n\nWrite at least 150 words.")
        ]
        case .ieltsTask2: [
            ("问题解决 · 工作时长", "In many countries, people are working longer hours than in the past. What are the causes of this? What can be done to address the problem?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words."),
            ("同意与否 · 公共交通", "Some people think governments should spend money on public transport rather than on building new roads. To what extent do you agree or disagree?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words."),
            ("利弊 · 网购与实体店", "Online shopping is gradually replacing shopping in high-street stores. Is this a positive or negative development?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words."),
            ("双边讨论 · 入学年龄", "Some people believe children should begin formal education at a very early age. Others think they should not start school until they are at least seven years old. Discuss both views and give your own opinion.\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words."),
            ("同意与否 · 旅游与文化", "International tourism brings economic benefits, but it also damages local cultures and environments. To what extent do you agree or disagree?\n\nGive reasons for your answer and include any relevant examples from your own knowledge or experience. Write at least 250 words.")
        ]
        case .kaoyanTranslation: [
            ("科学方法", "将下列五个英语句子译成通顺、准确的汉语。请保留编号。原创练习，每句按 2 分练习尺度评阅。\n\n1. Science advances not because scientists are always right, but because they are willing to discover where they are wrong.\n2. A theory that cannot be tested, however elegant it may seem, offers little more than an interesting story.\n3. What distinguishes a careful researcher is less the ability to collect data than the patience to question what the data actually show.\n4. Even the most reliable instruments are only as useful as the questions that guide their use.\n5. It was only after decades of failed experiments that the importance of the overlooked variable finally became clear."),
            ("城市与记忆", "将下列五个英语句子译成通顺、准确的汉语。请保留编号。原创练习，每句按 2 分练习尺度评阅。\n\n1. Old buildings matter to a city not merely as architecture, but as places where shared memories are stored.\n2. When a neighbourhood is redeveloped too quickly, residents may lose the sense of belonging that took generations to build.\n3. Planners who listen to local voices are more likely to create spaces that people actually want to use.\n4. A street that looks untidy to visitors may be precisely what gives residents their feeling of home.\n5. Preserving the past need not mean resisting change; it can mean choosing carefully what deserves to be carried forward."),
            ("技术与工作", "将下列五个英语句子译成通顺、准确的汉语。请保留编号。原创练习，每句按 2 分练习尺度评阅。\n\n1. Automation rarely eliminates work altogether; more often, it changes which tasks people are paid to perform.\n2. Workers who can combine technical knowledge with sound judgment are likely to remain in demand.\n3. The danger lies not in machines becoming more capable, but in institutions failing to help people adapt.\n4. Few predictions about the future of work have proved accurate, which is itself a reason for humility.\n5. Whether new technology widens or narrows inequality depends largely on the choices societies make about education and training.")
        ]
        case .kaoyan2Translation: [
            ("选择职业", "请将下列英语段落完整译成准确、通顺的汉语。原创英语二翻译练习，采用 15 分练习尺度。\n\nChoosing a career is often presented as a single decision made at the end of university, but for most people it is a gradual process. Early jobs teach us not only practical skills but also what kind of work environment suits us. Some discover that they enjoy working with people; others realise they prefer solving problems on their own. These discoveries rarely come from careful planning alone. They come from trying things, noticing how we feel, and being honest about what we learn. It is therefore worth treating the first few years of work as a period of exploration rather than a test that must be passed perfectly. Changing direction is not a sign of failure. In many cases, it shows that a person has paid attention to experience and is willing to act on it. A career built in this way may look less tidy on paper, but it is more likely to be satisfying."),
            ("博物馆的变化", "请将下列英语段落完整译成准确、通顺的汉语。原创英语二翻译练习，采用 15 分练习尺度。\n\nMuseums were once seen mainly as places for storing and displaying valuable objects. Visitors walked quietly past glass cases, read short labels and left. Today, many museums are trying to become more welcoming. They offer interactive exhibitions, evening events and activities designed for families. Some invite local residents to help decide what stories should be told. Digital tools allow people who cannot travel to explore collections online. These changes have brought in new audiences, especially young people who might otherwise never have visited. However, some critics worry that museums risk becoming places of entertainment rather than learning. The challenge is to find a balance: to make collections accessible and engaging without losing the careful research and thoughtful presentation that give museums their value."),
            ("旅行的意义", "请将下列英语段落完整译成准确、通顺的汉语。原创英语二翻译练习，采用 15 分练习尺度。\n\nTravel is often promoted as a way to escape daily life, but its greater value may lie in what it teaches us when we return. In an unfamiliar place, we notice details that we normally ignore: how people greet each other, how streets are organised, what is considered polite. These observations remind us that our own habits are only one way of living among many. Of course, a short trip does not make anyone an expert on another culture. Travellers who visit only famous sights and take the same photographs as everyone else may learn very little. The difference lies in attitude. Those who travel with curiosity and humility, who ask questions and listen to the answers, tend to come home with a wider view of the world and a clearer view of themselves.")
        ]
        case .cet6Translation: [
            ("高铁", "请将下面的汉语段落译成英语。原创翻译练习。\n\n过去十多年来，中国的高速铁路发展迅速，已经连接起全国大部分主要城市。高铁不仅缩短了城市之间的旅行时间，也改变了人们的生活方式。许多人选择在一座城市工作、在另一座城市生活，周末往返变得十分方便。高铁的发展还带动了沿线地区的经济，促进了旅游业和商业的繁荣。与此同时，中国在高铁建设和运营方面积累的经验，也为其他国家提供了有益的参考。"),
            ("中秋节", "请将下面的汉语段落译成英语。原创翻译练习。\n\n中秋节在农历八月十五，是中国重要的传统节日之一。这一天的月亮被认为是一年中最圆、最亮的，象征着团圆。按照传统，家人会聚在一起赏月、吃月饼，分享生活中的喜悦。在外工作或学习的人，即使无法回家，也常常通过电话或视频向家人表达思念。如今，月饼的口味越来越多样，但中秋节所承载的家庭观念和美好祝愿始终没有改变。"),
            ("志愿服务", "请将下面的汉语段落译成英语。原创翻译练习。\n\n近年来，越来越多的中国年轻人参与志愿服务。他们走进社区、学校和乡村，为老人提供陪伴，为儿童辅导功课，或者参与环境保护活动。大型体育赛事和文化活动中，也随处可见志愿者的身影。参与志愿服务不仅帮助了他人，也让年轻人增长了见识，提高了沟通和组织能力。许多志愿者表示，在付出的过程中，他们更加理解了社会，也找到了自身的价值。")
        ]
        }
    }
}
